### ISSUE TITLE
Remote GPIO

### ISSUE THREAD

**Issue by Ghannes** [thecode/ha-rpi_gpio#75]
Since HomeAssistant dropped **remote gpio** i'm looking for alternatives. So my new feature request is to add **remote GPIO** so that I can use GPIO of a remote PI - like I used to do in HA 2022.5 and earlier

**Comment by thecode** [comment]
Home assistant did not drop remote gpio, only local GPIO controls are not allowed.
See https://www.home-assistant.io/integrations/remote_rpi_gpio/
Everything that was dropped is already removed documentation was also removed. Any integrations you find now in Home Assistant is valid and is not going to be removed due to local GPIO control.
